Tree=
--0: 0",
--0: 1",
{branchname="example Lua tree",
--1: 2",
{branchname="Baumdatei",
--2: 3",
{branchname="C:\Tree\Tree_Python\Tree_Baum.lua",
--3: 2",
},
},
{branchname="Output",
--2: 3",
{branchname="C:\Tree\Tree_Python\Tree_Baum.lua",
--3: 2",
},
},
{branchname="Ordner",
--2: 3",
{branchname="C:\Tree\Tree_Python",
},
},
}
