= {appname} - DV-Konzept
Jens Kötterheinrich <jkh@beckmann-partner.de>
2018-02-20
:appversion: 1.0
:source-highlighter: coderay
:pdf-page-size: A4
:appname: DocumentationTree
:lang: de
:sectnums:
:toc:

ifdef::lang[include::attributes-{lang}.adoc[]]

== Allgemeines
=== Zweck und Struktur des Dokuments
Dieses Dokument beschreibt die Anwendung {appname}.
Die Anwendung wird als Bestandteil von Dokumentation von Datenbanken verwendet.
Mit diesem Dokument soll der Leser in die Lage versetzt werden,
- den Aufbau der Anwendung zu verstehen,
- die Aufgaben der Anwendung,
- das System über die Benutzeroberfläche bedienen zu können,
- die Schnittstellen zu anderen Systemen zu kennen,
- im Falle eines Systemfehlers die geeigneten Maßnahmen ergreifen zu können.

== Übersicht
Die Anwendung {appname} basiert auf der Java Standard Edition.
Es wird mindestens die Version 7 vorausgesetzt.
Bei der Anwendung handelt es sich um eine JavaFX-Anwendung.
Sie lässt sich mit einer Java Runtime (>= Version 7) starten.

== Funktionalität
Die Anwendung stellt folgende Funktionalitäten bereit:

- Öffnen und Parsen einer Datei mit LuaTable (später auch XML)
- Darstellung als Baumstruktur
- Markieren von Knoten in unterschiedlichen Farben zur schnellen Übersicht und Analyse

== Dateibeschreibungen
=== LuaTable
Eine Lua-Datei besteht aus Lua-Code.
Darin wird eine LuaTable erzeugt und zurückgegeben.
Der Aufbau der LuaTable basiert auf https://webserver2.tecgraf.puc-rio.br/iup/en/elem/iuptree.html[IupTree].

.Beispiel LuaTable
[source,lua]
----
example =
{branchname="example",
  {branchname="foo", 'Hello'},
  {branchname="bar", 'world!'}
}

return example
----

== Programmdesign
=== Ablauf
==== Auswahl einer Datei
Nach dem Start der Anwendung wird ein Dialog angezeigt, um eine Datei auszuwählen.
Die erlaubten Endungen der zu öffnenden Dateien sind _.lua_ und _.xml_.

==== Parsen einer ausgewählten Datei
Mit Hilfe des Frameworks

[source,xml]
----
<dependency>
    <groupId>org.luaj</groupId>
    <artifactId>luaj-jse</artifactId>
    <version>3.0.1</version>
</dependency>
----
wird die LuaTable geparst und eine Instanz von _org.luaj.vm2.LuaTable_ erzeugt.

==== Erzeugen eines Baums
Auf Basis der erzeugten Instanz der LuaTable werden TreeItems erzeugt.
Dabei werden die Elemente der LuaTable rekursiv ausgewertet.
Einzelne Knoten werden als _TreeItems_ erzeugt, die zu einer _TreeView_ hinzugefügt werden.
Standardmäßig werden Knoten immer aufgeklappt dargestellt.
Durch _state = 'COLLAPSED'_ kann für einen Knoten definiert werden, dass er initial nicht ausgeklappt dargestellt wird.


==== Darstellung

==== Knoten selektieren

==== Knoten markieren

==== Fehlerbehandlung

=== Benutzeroberfläche
